### ISSUE TITLE
Custom Sanitizing Methods

### ISSUE THREAD

**Issue by mikeel100** [zencart/documentation#221] opened 2020-04-26 22:20 UTC
Can you add PRODUCT_URL_REGEX as one of the custom methods of sanitizing?

I need it for off site image retrieval (I know...it's not the best practice but the off site images will act as IMG_ALT eventually).

I am making it work at the moment by modifying init_sanitize.php: 

//MIKE REMOVED FROM ARRAY BELOW - 'products_previous_image', 
$group = array('img_dir', 'products_image_manual', 'products_attributes_filename', 'manufacturers_image_manual');
$sanitizer->addSimpleSanitization('FILE_DIR_REGEX', $group);

//MIKE ADDED TO THE ARRAY BELOW 'products_previous_image'
$group = array('products_url', 'products_previous_image', 'manufacturers_url');
$sanitizer->addSimpleSanitization('PRODUCT_URL_REGEX', $group);

I have added a custom sanitize file to extra_datafiles but can't, for the life of me, figure out how to obtain the same results as changing the init_santitize file.

Thanks.

**Comment by scottcwilson** [comment] 2020-04-26 22:24
Can you work out how to do this with help from the forum and then create a PR for documentation?

**Comment by drbyte** [comment] 2020-04-27 01:42
@mikeel100 to clarify, you're wanting to bypass the built-in default rule assigned for that field, and apply a different one, right?

Does this work?
```php
$group = array('products_previous_image' => array('sanitizerType' => 'PRODUCT_URL_REGEX', 'method' => 'post', 'pages' => array('product')));
$sanitizer->addComplexSanitization($group);
```

I guess maybe the problem is that `init_sanitize.php` "calls" all the sanitizers it declares, without providing a way for you to add more rules to intercept/override.

The extra_datafiles approach makes the assumption that you're adding your own new fields, not trying to alter existing behavior. 🤔

**Comment by scottcwilson** [comment] 2020-05-05 12:08
Closing; not a doc issue.

**Closed by scottcwilson** 2020-05-05 12:08 UTC
